name: Deploy
on:
  push:
    branches: main
  pull_request:
    branches: main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Install Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Build step
        run: "deno task build"
        env:
          BASIC_AUTH: "dummy:dummy"
          CSV_URL: "https://example.com/dummy.csv"

      - name: Upload to Deno Deploy
        id: deploy
        run: deno deploy

      - uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.deploy.outputs.url }}}"
            await core.summary
              .addHeading('Deploy successful!')
              .addLink(url, url)
              .write()
